micronaut:
  application:
    name: rodrigoeduque
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/carro-grpc
    driverClassName: org.postgresql.Driver
    username: postgres
    password: '1234'
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true
